### ISSUE TITLE
3DAppVersionSpoofer

### ISSUE THREAD

**Issue by Ijsbergsla33** [0xkuj/0xkuj#1]
Hi,

I have iPhone XS running on 13.3 with Unc0ver jailbreak. After installing 3DAppVersionSpoofer, i immediately go into safemode. Thus, it’s crashing🧐. Any tips?

**Comment by 0xkuj** [comment]
Hey @Ijsbergsla33 ,
Please provide Springboard crash log produced by cr4shed so I can take a look.. doesn’t sounds like this tweak is causing the crash after respring

**Comment by Ijsbergsla33** [comment]
Do i need to send you the whole log? And if so, how do i do that? I says Spotlight is crashing, but 3DAppSpoofer is the cause. 
![EFC69EE2-248F-4552-89FE-F4A55A6C37AF](https://user-images.githubusercontent.com/47435738/175508339-0bb815ec-2afb-438d-9d1a-a0850ddfb26f.png)

**Comment by 0xkuj** [comment]
@Ijsbergsla33 
Oh spotlight does make sense. Yes hit view log, then paste it you can use pastebin.com

**Comment by Ijsbergsla33** [comment]
https://pastebin.com/25t0DDHF

**Comment by 0xkuj** [comment]
@Ijsbergsla33 thanks I’ll have a look.
What version is your tweak? Is it 1.0.2? Do you have other tweaks related to spotlight?

**Comment by Ijsbergsla33** [comment]
Thank you! It’s 1.0.2. I do have SpotlightLess11 as tweak; it removes the spotlight function. I removed that tweak and after that i installed 3DAppVersionSpoofer, but it remains crashing.

**Comment by 0xkuj** [comment]
@Ijsbergsla33 please test the new version (1.1 on havoc)
if it still crashes, try disabling the 3d menu via settings (added settings in 1.1) and see if that helps. if it does, let me know so i can understand where the crash is coming from (crash log is unclear..)

**Comment by Ijsbergsla33** [comment]
Thanks for helping me, i really appreciate it. I just went into Cydia to look for 1.1, but i still see version 1.0.2. Am i doing something wrong?

**Comment by 0xkuj** [comment]
@Ijsbergsla33 you are not doing something wrong, it is not approved by havoc yet, will take few hours probably.
if you know how, install the deb file from here using iFilza https://github.com/0xkuj/3DAppVersionSpoofer/raw/main/packages/com.0xkuj.3dappversionspoofer_1.1_iphoneos-arm.deb or just wait until it will be uploaded to havoc

**Comment by Ijsbergsla33** [comment]
I”ll wait. Thanks, hope it will work. My banking app does not work, because it does not support iOS 13 anymore. I have to be on 14+, so i hope your tweak works well.

**Comment by 0xkuj** [comment]
@Ijsbergsla33 not sure it will work, banking apps usually have deeper checks other than just the version number. are you able to download the app from the Appstore but when launching it you get an update message? or you cannot download the app saying it needs to have iOS 14? what is the name of the app?

**Comment by Ijsbergsla33** [comment]
The name of the app is ‘Rabobank’. It is a large bank in the Netherlands. 

I indeed receive a message when starting up the app. I only see the message: please update to iOS 14. Then i can’t proceed. If you are able to fix this specially for me, i am willing to pay you. It drives me crazy😂. I have an iPhone 12 laying around, but i have 14.7.1 on that which has not been jailbroken.

**Comment by 0xkuj** [comment]
Sounds like the classic use case this tweak solves. Are you using any kind of jb bypass? App is crashing for me on iOS 13 upon launch

**Comment by Ijsbergsla33** [comment]
Nope, not of something i’m aware at. I use the latest version of the Unc0ver jailbreak through 3UTools. I do have the tweak Choicy which bypasses jailbreak detection, but it does not work.

**Comment by 0xkuj** [comment]
@Ijsbergsla33 looks like we are in a bad spot, I managed to launch the app with choicy enabled (without loaded tweaks) so now it’s not crashing. But if no tweaks are loaded, the tweak can’t work so if you are not using choicy as you said maybe try to find out what you are using so I can test this for you in the meantime or try look for another solution

**Comment by Ijsbergsla33** [comment]
What do you mean with loaded tweaks? I don't mind deleting Choicy as it now has no function.

**Comment by 0xkuj** [comment]
@Ijsbergsla33 choicy has an option to launch app without tweaks, sometime it helps for crashes in apps with jb detection. IMO, choicy is enabled on this app in your case and if you delete choicy the app will crash. If I’m wrong, then you are maybe using jb detection bypass.. or in other case, what is the version Rabobank you currently have?

**Comment by Ijsbergsla33** [comment]
You are right, the Rabobank app crashes if i delete Choicy. How do i see which version i am currently using from the app? Normaly i would look into the info settings, but now the app crashes, i cant see which version i am on.

**Comment by 0xkuj** [comment]
@Ijsbergsla33 i investigated the app, and it looks like the newer version is using methods from the iOS 14.x SDK. In short - this means there is probably no way to bypass this forcing update banner as iOS 14 SDK and API is REQUIRED for this app to run. Sorry 😞 
Update 1.1 is now on havoc btw - so let’s try figure out the crash you are having by disabling the 3d action from prefs..

**Comment by Ijsbergsla33** [comment]
No problem, i´m very pleased with your help!
